"""empty message

Revision ID: 79b528da951b
Revises: d6d20a44b50c
Create Date: 2022-12-16 14:47:04.086299

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '79b528da951b'
down_revision = 'd6d20a44b50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_default',
                              existing_type=sa.INTEGER(),
                              type_=sa.Boolean(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_default',
                              existing_type=sa.Boolean(),
                              type_=sa.INTEGER(),
                              existing_nullable=True)

    # ### end Alembic commands ###
