"""add article model

Revision ID: 84430f4e6f57
Revises: 79b528da951b
Create Date: 2022-12-16 16:47:59.510974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84430f4e6f57'
down_revision = '79b528da951b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
